logging:
  level:
    root: info #default
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tester
    password: test
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop