logging:
  level:
    root: info #default
spring:
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:32052/cardb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api